import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  console.log(router)

  const onClickMoveToPage = (path: string) => () => {
    void router.push(path)
  }

  return (
    <>
      <Head>
        <title>리덕스-toolkit-thunk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>메인 홈 화면</div>
      <button onClick={onClickMoveToPage('01-redux-toolkit-thunk')}>ReduxToolkit-Thunk</button>
    </>
  )
}
